language: php

php: 
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION='2.0.*'
  - SYMFONY_VERSION='2.1.*'
  - SYMFONY_VERSION='2.2.*@dev'

branches:
  only:
    - master
    - develop

before_script:
  - export PATH=./bin:$PATH
  - export BEHAT_PARAMS='formatter[name]=progress'

  - curl http://getcomposer.org/installer | php
  - php composer.phar require --no-update symfony/symfony=$SYMFONY_VERSION
  - php composer.phar install --dev --prefer-source

script: behat --tags ~@php-version && behat --tags '@php'`php -r 'echo substr(phpversion(), 0, 3);'`
