language: php

php: [7.2, 7.3, 7.4]

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: SKIP_INTEROP='~@interop&&'
    - php: 7.2
      env: DEPENDENCIES='low'
    - php: 7.2
      env: SYMFONY_VERSION='^4.4'
    - php: 7.3
      env: SYMFONY_VERSION='^4.4'
    - php: 7.4
      env: SYMFONY_VERSION='^4.4'

before_install:
  - phpenv config-rm xdebug.ini || echo "XDebug is not enabled"

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;
  - if [ "$SKIP_INTEROP" != "" ]; then composer remove --dev --no-update container-interop/container-interop; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; fi;
  - export PATH=./bin:$PATH

script:
  - ./vendor/bin/phpunit
  - behat -fprogress --strict --tags "${SKIP_INTEROP}~@random"

before_deploy:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - export PATH=.:$PATH
  - rm -Rf ./vendor
  - composer install --no-dev -o
  - box.phar build

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: behat.phar
  skip_cleanup: true
  on:
    tags: true
    php: 5.6
