language: php

php: 
  - 5.3.2
  - 5.3
  - 5.4

branches:
  only:
    - master
    - develop

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: bin/behat -fprogress `php -r 'echo -1 === version_compare(PHP_VERSION, "5.4.0") ? "--tags ~@php540" : "";'`
